version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:4.2'
    volumes:
      - 'mongodb_data:/bitnami'
  parse:
    image: 'bitnami/parse:3'
    ports:
      - '1337:1337'
    volumes:
      - 'parse_data:/bitnami'
    depends_on:
      - mongodb
    environment:
      PARSE_HOST: localhost
      PARSE_PORT_NUMBER_NUMBER: 1337
      PARSE_MOUNT_PATH: /parse
      PARSE_APP_ID: PARSELOCAL
      PARSE_MASTER_KEY: LOCALMASTERKEY
      MONGODB_HOST: mongodb
      MONGODB_PORT_NUMBER: 27017
  parse-dashboard:
    image: 'bitnami/parse-dashboard:2'
    ports:
      - '4040:4040'
    volumes:
      - 'parse_dashboard_data:/bitnami'
    depends_on:
      - parse
    environment:
      PARSE_DASHBOARD_USER: admin
      PARSE_DASHBOARD_PASSWORD: admin
      PARSE_HOST: localhost
      PARSE_PROTOCOL: http
      PARSE_PORT_NUMBER: 1337
      PARSE_APP_ID: PARSELOCAL
      PARSE_MASTER_KEY: LOCALMASTERKEY
      PARSE_DASHBOARD_APP_NAME: ParseLocalDashboard
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
